version: "2"
services:
  container1:
    image: labimage
    command: /bin/bash -c "/mnt/scripts/box1.sh;while true; do echo 'alive' && sleep 60; done"
    networks:
      network1:
        ipv4_address: 192.168.10.2
    volumes:
        - .:/mnt
  container2:
    image: labimage
    command: /bin/bash -c "/mnt/scripts/box2.sh;while true; do echo 'alive' && sleep 60; done"
    networks:
      network1:
        ipv4_address: 192.168.10.3
      network2:
        ipv4_address: 192.168.20.2
    volumes:
        - .:/mnt
  container3:
    image: labimage
    command: /bin/bash -c "/mnt/scripts/box3.sh;while true; do echo 'alive' && sleep 60; done"
    networks:
      network2:
        ipv4_address: 192.168.20.3
      network3:
        ipv4_address: 192.168.30.2
    volumes:
        - .:/mnt
  container4:
    image: labimage
    command: /bin/bash -c "/mnt/scripts/box4.sh;while true; do echo 'alive' && sleep 60; done"
    networks:
      network3:
        ipv4_address: 192.168.30.3
      network4:
        ipv4_address: 192.168.40.2
    volumes:
        - .:/mnt
  container5:
    image: labimage
    command: /bin/bash -c "/mnt/scripts/box5.sh;while true; do echo 'alive' && sleep 60; done"
    networks:
      network4:
        ipv4_address: 192.168.40.3
    volumes:
        - .:/mnt
networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"
          gateway: "192.168.10.1"
  network2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.20.0/24"
          gateway: "192.168.20.1"
  network3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.30.0/24"
          gateway: "192.168.30.1"
  network4:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.40.0/24"
          gateway: "192.168.40.1"
